# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
import gmaps

# Google developer API key
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_file = "../output_data/cities.csv"
# output_data_file

weather_df = pd.read_csv(weather_file)

weatherpy_df = weather_df.drop(columns=["Unnamed: 0"])
weatherpy_df

,City,Country,Date,Lat,Lng,Humidity,Cloudiness,Wind Speed,Max Temp
0,north bend,US,2020-04-09 21:47:46,43.41,-124.22,87.0,90.0,12.75,50.00
1,kampot,KH,2020-04-09 21:47:49,10.62,104.18,64.0,91.0,5.95,87.06
2,kloulklubed,PW,2020-04-09 21:47:49,7.04,134.26,66.0,75.0,13.87,87.80
3,ushuaia,AR,2020-04-09 21:47:50,-54.80,-68.30,58.0,75.0,28.86,59.00
4,tiksi,RU,2020-04-09 21:47:50,71.69,128.87,93.0,87.0,20.89,31.57
...,...,...,...,...,...,...,...,...,...
629,stutterheim,ZA,2020-04-09 21:51:36,-32.57,27.42,93.0,83.0,3.36,59.00
630,hualmay,PE,2020-04-09 21:51:36,-11.10,-77.61,81.0,89.0,6.22,71.91
631,rajec-jestrebi,CZ,2020-04-09 21:51:36,49.41,16.64,65.0,20.0,4.70,48.00
632,tepetzintla,MX,2020-04-09 21:51:37,21.17,-97.83,91.0,18.0,3.18,73.09
633,bridgetown,BB,2020-04-09 21:49:05,13.10,-59.62,74.0,40.0,12.75,80.60

In [3]:
dataTypeSeries = weatherpy_df.dtypes
dataTypeSeries

City           object
Country        object
Date           object
Lat           float64
Lng           float64
Humidity      float64
Cloudiness    float64
Wind Speed    float64
Max Temp      float64
dtype: object

In [4]:
weatherpy_df = weatherpy_df.dropna(how="any")
weatherpy_df

,City,Country,Date,Lat,Lng,Humidity,Cloudiness,Wind Speed,Max Temp
0,north bend,US,2020-04-09 21:47:46,43.41,-124.22,87.0,90.0,12.75,50.00
1,kampot,KH,2020-04-09 21:47:49,10.62,104.18,64.0,91.0,5.95,87.06
2,kloulklubed,PW,2020-04-09 21:47:49,7.04,134.26,66.0,75.0,13.87,87.80
3,ushuaia,AR,2020-04-09 21:47:50,-54.80,-68.30,58.0,75.0,28.86,59.00
4,tiksi,RU,2020-04-09 21:47:50,71.69,128.87,93.0,87.0,20.89,31.57
...,...,...,...,...,...,...,...,...,...
629,stutterheim,ZA,2020-04-09 21:51:36,-32.57,27.42,93.0,83.0,3.36,59.00
630,hualmay,PE,2020-04-09 21:51:36,-11.10,-77.61,81.0,89.0,6.22,71.91
631,rajec-jestrebi,CZ,2020-04-09 21:51:36,49.41,16.64,65.0,20.0,4.70,48.00
632,tepetzintla,MX,2020-04-09 21:51:37,21.17,-97.83,91.0,18.0,3.18,73.09
633,bridgetown,BB,2020-04-09 21:49:05,13.10,-59.62,74.0,40.0,12.75,80.60

In [5]:
dataTypeSeries = weatherpy_df.dtypes
dataTypeSeries

City           object
Country        object
Date           object
Lat           float64
Lng           float64
Humidity      float64
Cloudiness    float64
Wind Speed    float64
Max Temp      float64
dtype: object

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
#configure gkey
gmaps.configure(api_key=g_key)

#lat and lng coordinates
coordinates = weatherpy_df[["Lat", "Lng"]]

#humidity
humidity = weatherpy_df["Humidity"].astype(float)

In [7]:

# Customize the size of the figure
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

In [8]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(coordinates, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:
ideal_temp_df = weatherpy_df.loc[pd.to_numeric(weatherpy_df["Max Temp"]).astype(float).between(74, 78, inclusive=False)]

In [10]:
ideal_temp_wind_df = ideal_temp_df.loc[pd.to_numeric(ideal_temp_df["Wind Speed"]).astype(float) <10]

In [11]:
ideal_temp_wind_cloud_df = ideal_temp_wind_df.loc[pd.to_numeric(ideal_temp_wind_df["Cloudiness"]).astype(float) <50]

In [12]:
ideal_vacay_df = ideal_temp_wind_df.loc[pd.to_numeric(ideal_temp_wind_df["Humidity"]).astype(float) <70]
ideal_vacay_df

,City,Country,Date,Lat,Lng,Humidity,Cloudiness,Wind Speed,Max Temp
97,port alfred,ZA,2020-04-09 21:48:22,-33.59,26.89,51.0,98.0,6.93,74.28
130,xichang,CN,2020-04-09 21:48:33,27.90,102.26,17.0,43.0,8.16,76.42
163,longyan,CN,2020-04-09 21:48:45,25.11,117.02,38.0,7.0,5.55,76.80
180,san patricio,MX,2020-04-09 21:48:54,19.22,-104.70,54.0,4.0,4.29,76.57
228,coahuayana,MX,2020-04-09 21:45:08,18.73,-103.68,41.0,0.0,3.18,76.59
364,bako,ET,2020-04-09 21:49:56,5.78,36.57,45.0,48.0,2.33,74.30
403,leiyang,CN,2020-04-09 21:50:10,26.40,112.86,59.0,97.0,4.56,77.34
465,jiaojiang,CN,2020-04-09 21:50:35,28.68,121.44,43.0,1.0,3.00,75.00
489,ouadda,CF,2020-04-09 21:50:43,8.08,22.40,59.0,89.0,1.32,77.92
575,dalbandin,PK,2020-04-09 21:51:15,28.89,64.41,21.0,10.0,9.31,77.77
582,wilmington island,US,2020-04-09 21:51:17,32.00,-80.97,64.0,1.0,8.05,75.20

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [13]:
hotel_df = pd.DataFrame(ideal_vacay_df, columns=["City", "Country", "Lat", "Lng", "Humidity", "Cloudiness", "Wind Speed", "Max Temp"])
hotel_df

,City,Country,Lat,Lng,Humidity,Cloudiness,Wind Speed,Max Temp
97,port alfred,ZA,-33.59,26.89,51.0,98.0,6.93,74.28
130,xichang,CN,27.90,102.26,17.0,43.0,8.16,76.42
163,longyan,CN,25.11,117.02,38.0,7.0,5.55,76.80
180,san patricio,MX,19.22,-104.70,54.0,4.0,4.29,76.57
228,coahuayana,MX,18.73,-103.68,41.0,0.0,3.18,76.59
364,bako,ET,5.78,36.57,45.0,48.0,2.33,74.30
403,leiyang,CN,26.40,112.86,59.0,97.0,4.56,77.34
465,jiaojiang,CN,28.68,121.44,43.0,1.0,3.00,75.00
489,ouadda,CF,8.08,22.40,59.0,89.0,1.32,77.92
575,dalbandin,PK,28.89,64.41,21.0,10.0,9.31,77.77
582,wilmington island,US,32.00,-80.97,64.0,1.0,8.05,75.20

In [14]:
hotel_df['Hotel Name'] = ""
hotel_df

,City,Country,Lat,Lng,Humidity,Cloudiness,Wind Speed,Max Temp,Hotel Name
97,port alfred,ZA,-33.59,26.89,51.0,98.0,6.93,74.28,
130,xichang,CN,27.90,102.26,17.0,43.0,8.16,76.42,
163,longyan,CN,25.11,117.02,38.0,7.0,5.55,76.80,
180,san patricio,MX,19.22,-104.70,54.0,4.0,4.29,76.57,
228,coahuayana,MX,18.73,-103.68,41.0,0.0,3.18,76.59,
364,bako,ET,5.78,36.57,45.0,48.0,2.33,74.30,
403,leiyang,CN,26.40,112.86,59.0,97.0,4.56,77.34,
465,jiaojiang,CN,28.68,121.44,43.0,1.0,3.00,75.00,
489,ouadda,CF,8.08,22.40,59.0,89.0,1.32,77.92,
575,dalbandin,PK,28.89,64.41,21.0,10.0,9.31,77.77,
582,wilmington island,US,32.00,-80.97,64.0,1.0,8.05,75.20,

In [49]:
params = { 
    "radius": 5000,
    "type": "hotel",
    "key": g_key,
}
# Use the lat/lng to identify airports
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    
    # get city from df
    city_name = row['City']

    # change location each iteration while leaving original params in place(param from google)
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # make request and print url
    hotel_name = requests.get(base_url, params=params)

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
    #pprint(response)

    # extract results
    results = response
    #pprint(results)
    
    try:
        
        hotel_df.loc[index, 'Hotel Name'] = results['results'][1]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 97: port alfred.
------------
Retrieving Results for Index 130: xichang.
------------
Retrieving Results for Index 163: longyan.
------------
Retrieving Results for Index 180: san patricio.
------------
Retrieving Results for Index 228: coahuayana.
------------
Retrieving Results for Index 364: bako.
------------
Retrieving Results for Index 403: leiyang.
------------
Retrieving Results for Index 465: jiaojiang.
------------
Retrieving Results for Index 489: ouadda.
Missing field/result... skipping.
------------
Retrieving Results for Index 575: dalbandin.
------------
Retrieving Results for Index 582: wilmington island.
------------

In [50]:
hotel_df

,City,Country,Lat,Lng,Humidity,Cloudiness,Wind Speed,Max Temp,Hotel Name
97,port alfred,ZA,-33.59,26.89,51.0,98.0,6.93,74.28,The Halyards Hotel
130,xichang,CN,27.90,102.26,17.0,43.0,8.16,76.42,Xichang Real Estate Administration Bureau
163,longyan,CN,25.11,117.02,38.0,7.0,5.55,76.80,供销大厦
180,san patricio,MX,19.22,-104.70,54.0,4.0,4.29,76.57,Hotel Cabo Blanco
228,coahuayana,MX,18.73,-103.68,41.0,0.0,3.18,76.59,Chonita Bananas
364,bako,ET,5.78,36.57,45.0,48.0,2.33,74.30,Omo Valley TOURS
403,leiyang,CN,26.40,112.86,59.0,97.0,4.56,77.34,杜甫墓
465,jiaojiang,CN,28.68,121.44,43.0,1.0,3.00,75.00,Taizhou International Shangwu Square
489,ouadda,CF,8.08,22.40,59.0,89.0,1.32,77.92,Ouadda
575,dalbandin,PK,28.89,64.41,21.0,10.0,9.31,77.77,Dhq Hospital
582,wilmington island,US,32.00,-80.97,64.0,1.0,8.05,75.20,The UPS Store

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map